version: '3.8'

services:
  admission-backend:
    container_name: "${PREFIX}_admission-backend"
    build: .
    ports:
      - "4443:4000"
    env_file:
      - ../.admission-env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - kidzania-park-operation_backend
    depends_on:
      - redis
      - postgres

networks:
  kidzania-park-operation_backend:
    external: true
