version: '3.8'

services:
  admission-backend:
    container_name: "${PREFIX:-admission}-backend-${ENV:-dev}"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    image: ${DOCKER_REGISTRY:-localhost}/${PREFIX:-admission}-backend:${TAG:-latest}
    ports:
      - "${HOST_PORT:-4443}:${CONTAINER_PORT:-4000}"
    env_file:
      - ../.admission-env
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    networks:
      - kidzania-park-operation_backend
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:${CONTAINER_PORT:-4000}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  kidzania-park-operation_backend:
    external: true