version: '3.8'

services:
  admission-backend:
    image: admission-backend:${TAG:-latest}
    container_name: kidzania-park-operation-admission-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
    ports:
      - "${HOST_PORT:-4443}:${CONTAINER_PORT:-4000}"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - API_KEY=${API_KEY} 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:${CONTAINER_PORT:-4000}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  backend:
    external: true
    name: kidzania-park-operation_backend