version: '3.8'

services:
  admission-backend:
    container_name: ${PREFIX}-admission-backend
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ../.admission-env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$POSTGRES_DB
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    depends_on:
      - kidzania-park-operation-postgres
      - kidzania-park-operation-redis
